### ISSUE TITLE
Search highlight is too subtle

### ISSUE THREAD

**Issue by rik** [hichemfantar/halcyon-zed#1]
Thanks for bringing this theme to Zed!

Compared to the VSCode version, I'm struggling to identify search matches because of the highlight being too subtle.

<details>
<summary>VScode</summary>

![VSCode](https://github.com/user-attachments/assets/a7c75ea0-48f4-442d-8c7b-00d5debf9a1b)

</details>

<details>
<summary>Zed</summary>

![Zed](https://github.com/user-attachments/assets/e1a0fac8-2877-451d-ba5c-444ccc6ba479)
</details>

**Comment by clicktodev** [comment]
I can't find the property to change it. feel free to try and open a PR.
just put the json file in `/Users/username/.config/zed/themes/halcyon-zed-theme.json` and zed will use the values in that file. It should update in realtime so no need to restart zed with each change.

**Comment by clicktodev** [comment]
I believe this is what you meant

![image](https://github.com/user-attachments/assets/b4401ee4-7b0a-439f-ae89-b02ffed3c8d8)

**Comment by rik** [comment]
If you want to compare, I left screenshots in my initial descriptions (you can open them by clicking the arrow next to each editor).

**Comment by clicktodev** [comment]
Fixed in my latest commit
